apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slurm-metrics-gateway.fullname" . }}
  labels:
    {{- include "slurm-metrics-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "slurm-metrics-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slurm-metrics-gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: gateway
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
