apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm-metrics-gateway.fullname" . }}
  labels:
    {{- include "slurm-metrics-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "slurm-metrics-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
